branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: awseb-node-sample-dev
environment-defaults:
  awseb-node-sample-dev:
    branch: null
    repository: null
global:
  application_name: awseb-node-sample
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
